name: Publish pages ready to post

on:
  #schedule:
    #- cron: '0 19 * * 6' # 16:00 BRT Sábados
    #- cron: '0 21 * * 0-5' # 18:00 BRT outros dias
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
          token: "${{ secrets.JEKYLL_PAT }}"
      - name: Publish Posts
        shell: bash
        run: |
          dateString=$(date -I -d "2021-04-24")
          git config --global user.email "eu@davicruz.com"
          git config --global user.name "Davi Cruz"
          # Determine posts to be published
          toPublish=$(find ./ -name $dateString* )
          if [ $(echo $toPublish | wc -l) -gt 1 ]; then
          for i in $(find ./ -name $dateString* ); do
          postName=$(echo $i | awk -F'[/-.]' '{print toupper($9) " " toupper($10)'})
          echo $postName
          d=$(echo $i | sed 's/_drafts/_i18n/' | sed 's/BR/BR\/_posts/' | sed 's/US/US\/_posts/')
          mv $i $d
          done
          # Commit _drafts changes
          cd ./_drafts
          git status
          git add *
          git commit -m "Published Post $postName"
          git push origin main
          # Commit project changes
          cd ..
          git status
          git add *
          git commit -m "Published Post $postName"
          git push origin master
          fi