name: Publish pages ready to post

on:
  schedule:
    #- cron: '0 19 * * 6' # 16:00 BRT Sabados
    #- cron: '0 21 * * 0-5' # 18:00 BRT outros dias
    - cron: '* 22 * * *' # Testing only

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule sync --recursive
        git -c "http.extraheader=Authorization: basic ${{ secrets.GITHUB_TOKEN }}" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Publish Posts
      shell: bash
      run: |
        dateString=$(date -I)
        # List all posts to be published
        for i in $(find ./ -name $dateString*); do;
          d=$(echo $i | sed 's/_drafts/_i18n/' | sed 's/BR/BR\/_posts/')
          mv $i $d
        done
        
        # Commit project changes
        git add *
        git commit -m "Published Post"
        git push origin master